# Generated by Django 3.2.9 on 2021-12-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
