# Generated by Django 3.2.9 on 2021-12-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='practica',
            fields=[
                ('idpractica', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=30)),
                ('pregunta1', models.CharField(max_length=80)),
                ('pregunta2', models.CharField(max_length=80)),
                ('pregunta3', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('premium', models.BooleanField()),
            ],
        ),
    ]
