# Generated by Django 3.2.9 on 2021-12-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCursoPython', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='respuesta1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='practica',
            name='respuesta2',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='practica',
            name='respuesta3',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='practica',
            name='pregunta1',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='practica',
            name='pregunta2',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='practica',
            name='pregunta3',
            field=models.CharField(max_length=160),
        ),
    ]
