# Generated by Django 3.2.9 on 2021-12-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCursoPython', '0002_auto_20211130_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practica',
            name='pregunta1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practica',
            name='pregunta2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practica',
            name='pregunta3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practica',
            name='tema',
            field=models.CharField(max_length=40),
        ),
    ]
